services:
    github.client:
        class: Github\Client
        calls:
            - ['authenticate', [%github.token%, null, 'http_token']]

    github.cloner:
        class: Akeneo\Git\ProjectCloner
        arguments:
            - @akeneo.system.executor

    github.pull_request_creator:
        class: Akeneo\Git\PullRequestCreator
        arguments:
            - @akeneo.system.executor
            - @github.client
