services:
    github.client:
        class: Github\Client
        calls:
            - ['authenticate', [%github.token%, null, 'http_token']]

    github.cloner:
        class: Akeneo\Git\ProjectCloner
        arguments:
            - '@github.client'
            - '@akeneo.system.executor'
            - %github.fork_owner%
            - %github.owner%
            - %github.repository%

    github.pull_request_creator:
        class: Akeneo\Git\PullRequestCreator
        arguments:
            - '@akeneo.system.executor'
            - '@github.client'
            - %github.fork_owner%
            - %github.owner%
            - %github.repository%
