services:
    logger.handler:
        class: Monolog\Handler\StreamHandler
        arguments:
            - %nelson.log_file%
            - 200

    logger:
        class: Monolog\Logger
        arguments:
            - 'nelson'
            - [@logger.handler]

    console_logger:
        class: Monolog\Logger
        arguments:
            - 'nelson'

    event_dispatcher:
        class: Symfony\Component\EventDispatcher\EventDispatcher

    system.executor:
        class: Akeneo\System\Executor
        arguments:
            - @logger
            - %nelson.log_file%
