services:
    logger.handler:
        class: Monolog\Handler\StreamHandler
        arguments:
            - app/logs/application.log
            - 200

    logger:
        class: Monolog\Logger
        arguments:
            - 'nelson'
            - [@logger.handler]

    console_logger:
        class: Monolog\Logger
        arguments:
            - 'nelson'

    event_dispatcher:
        class: Symfony\Component\EventDispatcher\EventDispatcher
