services:
    akeneo.system.translation_files.provider:
        class: Akeneo\System\TranslationFilesProvider
        arguments:
            - %system.finder_options%
            - %system.pattern_suffix%

    akeneo.system.target_resolver:
        class: Akeneo\System\TargetResolver
        arguments:
            - %system.target_rules%

    akeneo.system.executor:
        class: Akeneo\System\Executor
        arguments:
            - @logger

    akeneo.system.translation_files.cleaner:
        class: Akeneo\System\TranslationFilesCleaner

    # TODO Move this filename
    akeneo.system.my_custom_subscriber:
        class: Akeneo\MyCustomSubscriber
