services:
    akeneo.system.translation_files.provider:
        class: Akeneo\System\TranslationFilesProvider
        arguments:
            - %system.finder_options%
            - %system.pattern_suffix%

    akeneo.system.target_resolver:
        class: Akeneo\System\TargetResolver
        arguments:
            - %system.target_rules%
