github:
    # The name of your project on github
    repository: Sylius
    # The owner of the project on github
    owner: Sylius
    # The owner of the user who will create pull requests with new translations
    fork_owner: SyliusBot
    # The github token of this user
    token: OOPSIE
    # The branches to manage.
    # {'githubBranch':'crowdinFolder'} or [branch]
    # Where branch is the same name between Github and Crowdin folder
    # Use [~] if you don't want branch management. Default: [~]
    branches: ['1.0', '1.1', 'master']

crowdin:
    # The name of your project on Crowdin
    project: sylius
    # The key of your project on Crowdin
    key: OOPSIE
    # You can set a minimum to only pull full-translated languages (from 0 to 100, default: 0)
    min_translated_progress: 0
    # Only the folders listed below are used to compute the minimal translations. If you don't want this
    # feature, use ~ instead, it will compute the minimal translation with all the available folders.
    folders: ~
    download:
        base_dir: /private/tmp/nelson-download
        # By default, specific region languages are removed; mapping is done by the 2 first letters.
        # Insert here special mappings, like this:
        locale_map:
            zh_CN: zh_CN
            zh_TW: zh_TW
            de_CH: de_CH
            sr_CS: sr_CS
            pt_BR: pt_BR
    upload:
        base_dir: /private/tmp/nelson-upload

nelson:
    # These options are passed to a Symfony Finder to find your original translation files.
    # Be careful, only select your origin language files (for example, only *.en.yml files).
    finder_options:
        in: 'src/'
        notPath: '/Test/'
        name: '*.en.yml'
    # You can map your github project file paths to crowdin file paths. These next parameters are used in
    # a str_replace function.
    target_rules:
        'src/Sylius/Bundle/AddressingBundle/Resources/translations': 'AddressingBundle'
        'src/Sylius/Bundle/AdminBundle/Resources/translations': 'AdminBundle'
        'src/Sylius/Bundle/AttributeBundle/Resources/translations': 'AttributeBundle'
        'src/Sylius/Bundle/ChannelBundle/Resources/translations': 'ChannelBundle'
        'src/Sylius/Bundle/CoreBundle/Resources/translations': 'CoreBundle'
        'src/Sylius/Bundle/CurrencyBundle/Resources/translations': 'CurrencyBundle'
        'src/Sylius/Bundle/CustomerBundle/Resources/translations': 'CustomerBundle'
        'src/Sylius/Bundle/LocaleBundle/Resources/translations': 'LocaleBundle'
        'src/Sylius/Bundle/OrderBundle/Resources/translations': 'OrderBundle'
        'src/Sylius/Bundle/PaymentBundle/Resources/translations': 'PaymentBundle'
        'src/Sylius/Bundle/PayumBundle/Resources/translations': 'PayumBundle'
        'src/Sylius/Bundle/ProductBundle/Resources/translations': 'ProductBundle'
        'src/Sylius/Bundle/PromotionBundle/Resources/translations': 'PromotionBundle'
        'src/Sylius/Bundle/ResourceBundle/Resources/translations': 'ResourceBundle'
        'src/Sylius/Bundle/ReviewBundle/Resources/translations': 'ReviewBundle'
        'src/Sylius/Bundle/ShippingBundle/Resources/translations': 'ShippingBundle'
        'src/Sylius/Bundle/ShopBundle/Resources/translations': 'ShopBundle'
        'src/Sylius/Bundle/TaxationBundle/Resources/translations': 'TaxationBundle'
        'src/Sylius/Bundle/TaxonomyBundle/Resources/translations': 'TaxonomyBundle'
        'src/Sylius/Bundle/UiBundle/Resources/translations': 'UiBundle'
        'src/Sylius/Bundle/UserBundle/Resources/translations': 'UserBundle'
    # Optional: You can put your translations in a folder when you download archive from Crowdin.
    # Can be useful when your Crowdin project is linked to several github repositories.
    pattern_suffix: ~
    # Optional: log the application executions in this file.
    log_file: 'app/logs/application.log'
    # Optional: translate logs. Default: 'en_US'
    log_locale: 'en_US'
